### ISSUE TITLE
Redesign arm

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Mechanical-2023#16]
arm needs to be way stiffer, including standoff/spacer mounts or full redesign

**Comment by theblueone111** [comment]
updated outer links, need to update the lightening pattern and add hole pattern on mid links

**Comment by theblueone111** [comment]
need to print all the arm plate spacers

**Comment by MayaEnriquez** [comment]
Current To Do:
spacers /3d printed u channel? bearing sizes + belt tensioning

**Comment by MayaEnriquez** [comment]
Currently Assembled for testing, future revision needs arm PCBs (hand Board + Bread-board + arm breakouts(3)) to have cases + wire management

**Comment by PugslyFTW** [comment]
currently working on shrouds for pcbs to protect the pcbs from dust
