### ISSUE TITLE
electronic Models

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Mechanical-2023#18]
all the electronics need to be modeled such that they can be arranged in the chassis

**Comment by MayaEnriquez** [comment]
notes on what needs modeling: 
Science: verify science dosing pump/vacuum pump
Comms Tower(Mission Control Bin): 
Battery/mount
Transciever(Rocket 900?)
PoE connection
Access Point( after verification with mission control)
Comm Tower Case/ Wiring Setup
