### ISSUE TITLE
Manufacture all new plates for new motors and redesigns

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Mechanical-2023#20]
need to manufacture all the new plates

**Comment by theblueone111** [comment]
new plates cant be made until all design changes are confirmed

**Comment by theblueone111** [comment]
arm is gunna be nade to work with new motors for this version but still be redesigned for after the video

**Comment by theblueone111** [comment]
all parts sent to ISM. waiting on response

**Comment by kammce** [comment]
EXCITING!!! 🎉🎉🎉

**Comment by theblueone111** [comment]
Talked with ims manager and he received the parts. the last set were waterjet and i asked that they laser cut this set for better cut quality.

**Comment by theblueone111** [comment]
1/8th arm plates arriving feb 18th everything else arriving feb 21-25
