### ISSUE TITLE
Science Robot CAD NTD 

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Mechanical-2023#22]
The CAD needs to be fully fleshed out.

**Comment by tommytn54** [comment]
I Need to make funnel
Science PCB case

**Comment by theblueone111** [comment]
magnets need to be designed into the revolver. the hall effects need to be located in the enclosure for the revolver positioning. all components need to be mounted to the enclosure and located

**Comment by MayaEnriquez** [comment]
printed  latest version for SAR video, future reccomendation: science pcb not on the bottom of the case

**Comment by MayaEnriquez** [comment]
magnets in gear, gear remesh, pcb reinstall, & pump install

**Comment by MayaEnriquez** [comment]
gas sensor install into gas chamber? + remodel for pressure sensor https://www.sparkfun.com/products/19096

**Comment by MayaEnriquez** [comment]
holes n zipties for pump on top
