### ISSUE TITLE
Prototyping/Logistics Behind Machinery

### ISSUE THREAD

**Issue by MayaEnriquez** [SJSURoboticsTeam/URC-Mechanical-2023#39]
Items:
Fred has agreed to do simple pieces, try to meet in person?
Email Viswanathan about the machine or shop access, + FD & O? ME 42?
Waterjet vs CNC Router? Which can we convince them to use?

**Comment by kammce** [comment]
Lets split this up into multiple issues. We have an issue for logistics for Fred, another for our own equipment. @MayaEnriquez.
