### ISSUE TITLE
Purchase Ryobi Battery Mount

### ISSUE THREAD

**Issue by MayaEnriquez** [SJSURoboticsTeam/URC-Mechanical-2023#42]
Buy batttery mount ( bc we could not buy prongs for our version)

**Comment by MayaEnriquez** [comment]
i think this is the link
https://www.amazon.com/Adapter-Lithium-ion-Battery-Connector-Robotics/dp/B07J17Z42R/ref=sr_1_40?crid=1V86VC9B8S03H&keywords=40v+drill+battery+mount&qid=1682993813&sprefix=40+v+drill+batter+mount%2Caps%2C187&sr=8-40

**Comment by MayaEnriquez** [comment]
@swiftrax

**Comment by swiftrax** [comment]
purchased
