### ISSUE TITLE
Design Battery Mount

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Mechanical-2023#7]
The mount for the ryobi 40v batteries needs to be designed, prototyped, manufactured, and tested

**Comment by theblueone111** [comment]
make the battery retionion .5mm looser all around

**Comment by theblueone111** [comment]
make sure the battery is removable and not not hit the suspension mount during removal

**Comment by MayaEnriquez** [comment]
rotunda drive and arm battery mount have their own flat and angled versions now, drive battery clearance issue should be fixed, arm battery needs to be changed with comm tower

**Comment by MayaEnriquez** [comment]
Updated mount to lower material

**Comment by MayaEnriquez** [comment]
Angled mount has heat insert slots and Velcro channel, flat mount is not changed yet.

**Comment by theblueone111** [comment]
purchased battery holder from amazon to expedite process as well due to lack of connector supplier

**Comment by theblueone111** [comment]
battery mounts arriving feb 22 - 24
