### ISSUE TITLE
Design Main Power Distribution Dorito Case

### ISSUE THREAD

**Issue by theblueone111** [SJSURoboticsTeam/URC-Mechanical-2023#8]
The main Dorito PCB needs a case to be designed around it with 3D printing and PLA

**Comment by theblueone111** [comment]
need to get updated model of the pcb as the one we currently used does not have the other two motor out connectors

**Comment by theblueone111** [comment]
need tp update lid design to accommodate the usb out headers

**Comment by MayaEnriquez** [comment]
Account for fuses With New Lid

**Comment by MayaEnriquez** [comment]
waiting on new dorito design

**Comment by MayaEnriquez** [comment]
new dorito design recieved, model made, not printed

**Comment by MayaEnriquez** [comment]
printed

**Comment by MayaEnriquez** [comment]
edits made for convenience, waiting on mounting schematic/plan to make mounting holes to be locked into place

**Comment by MayaEnriquez** [comment]
Waiting on feedback/ Dorito changes were mentioned.

**Comment by MayaEnriquez** [comment]
new dorito again

**Comment by MayaEnriquez** [comment]
mounted to chassis bottom
